Repository sbarguil/Testing-framework, pull requests merged in 2020-08, with the labels that each got.

#8 [Pytest] Interfaces config tests and initial framework structure
  .idea/.gitignore
  .idea/Testing-framework.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/vcs.xml
  AutomationFramework/README.md
  AutomationFramework/__init__.py
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/__init__.py
  AutomationFramework/page_objects/base/__init__.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/__init__.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_config.yml
  AutomationFramework/test_cases/templates/if_config_description.xml
  AutomationFramework/test_cases/templates/if_config_enabled.xml
  AutomationFramework/test_cases/templates/if_config_loopback_mode.xml
  AutomationFramework/test_cases/templates/if_config_mtu.xml
  AutomationFramework/test_cases/templates/if_config_tpid.xml
  AutomationFramework/test_cases/templates/if_config_type.xml
  AutomationFramework/tests/__init__.py
  AutomationFramework/tests/test_if_config.py
  AutomationFramework/utils/__init__.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest

#18 [issue_10] Tear down implemented with a fixture
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_config.yml
  AutomationFramework/test_cases/templates/if_config_loopback_mode.xml
  AutomationFramework/tests/test_if_config.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest

#20 [pytest] if_ethernet tests
  AutomationFramework/.gitignore
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_ethernet.yml
  AutomationFramework/test_cases/templates/if_ethernet_port_speed_state.xml
  AutomationFramework/tests/base_test.py
  AutomationFramework/tests/test_if_ethernet.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest

#19 [test_cases]New yml if_ethernet
  AutomationFramework/.gitignore
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_ethernet.yml
  AutomationFramework/test_cases/templates/if_ethernet_aggregate_id.xml
  AutomationFramework/test_cases/templates/if_ethernet_auto_negotiate.xml
  AutomationFramework/test_cases/templates/if_ethernet_duplex_mode.xml
  AutomationFramework/test_cases/templates/if_ethernet_port_speed.xml
  AutomationFramework/test_cases/templates/if_ethernet_port_speed_state.xml
  AutomationFramework/tests/base_test.py
  AutomationFramework/tests/test_if_ethernet.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: test_case

#46 [pytest] If_subif tests implementd
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_ethernet.yml
  AutomationFramework/test_cases/if_subif.yml
  AutomationFramework/test_cases/templates/if_subif_description.xml
  AutomationFramework/test_cases/templates/if_subif_dhcp_client.xml
  AutomationFramework/test_cases/templates/if_subif_enabled.xml
  AutomationFramework/test_cases/templates/if_subif_inner_outer_vlan_id.xml
  AutomationFramework/test_cases/templates/if_subif_ip_prefix_length.xml
  AutomationFramework/test_cases/templates/if_subif_ip_state.xml
  AutomationFramework/test_cases/templates/if_subif_match_vlan_id.xml
  AutomationFramework/test_cases/templates/if_subif_mtu.xml
  AutomationFramework/test_cases/templates/if_subif_origin.xml
  AutomationFramework/test_cases/templates/if_subif_type.xml
  AutomationFramework/test_cases/templates/if_subif_vlan_id.xml
  AutomationFramework/tests/test_if_subif.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest

#48 [pytest] If status tests
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_status.yml
  AutomationFramework/test_cases/templates/if_status_admin_status.xml
  AutomationFramework/test_cases/templates/if_status_enabled.xml
  AutomationFramework/test_cases/templates/if_status_name.xml
  AutomationFramework/test_cases/templates/if_status_oper_status.xml
  AutomationFramework/tests/test_if_status.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: Done, pytest

#56 [pytest] Tests implemented, 2 remaining
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_bgp.yml
  AutomationFramework/test_cases/templates/ni_bgp_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_description.xml
  AutomationFramework/test_cases/templates/ni_bgp_enabled.xml
  AutomationFramework/test_cases/templates/ni_bgp_export_policy.xml
  AutomationFramework/test_cases/templates/ni_bgp_import_policy.xml
  AutomationFramework/test_cases/templates/ni_bgp_local_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_multihop_ttl.xml
  AutomationFramework/test_cases/templates/ni_bgp_neighbor_address.xml
  AutomationFramework/test_cases/templates/ni_bgp_peer_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_peer_type.xml
  AutomationFramework/test_cases/templates/ni_bgp_remove_private_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_router_id.xml
  AutomationFramework/tests/network_instance/test_ni_bgp.py
Labels: pytest

#60 [pytest] NI protocol instances tests
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_protocol_instances.yml
  AutomationFramework/test_cases/templates/ni_protocol_instances_creation.xml
  AutomationFramework/test_cases/templates/ni_protocol_instances_enabled.xml
  AutomationFramework/tests/network_instance/test_ni_protocol_instances.py
Labels: pytest

#61 [pytest] Ni ospf tests implemented, 1 skipped
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_ospf.yml
  AutomationFramework/test_cases/templates/ni_ospf_authentication_type.xml
  AutomationFramework/test_cases/templates/ni_ospf_id.xml
  AutomationFramework/test_cases/templates/ni_ospf_identifier.xml
  AutomationFramework/test_cases/templates/ni_ospf_interface.xml
  AutomationFramework/test_cases/templates/ni_ospf_network_type.xml
  AutomationFramework/test_cases/templates/ni_ospf_passive.xml
  AutomationFramework/test_cases/templates/ni_ospf_router_id.xml
  AutomationFramework/test_cases/templates/ni_ospf_subinterface.xml
  AutomationFramework/tests/network_instance/test_ni_ospf.py
Labels: pytest

#63 [pytest] ni static tests implemented
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_static.yml
  AutomationFramework/test_cases/templates/ni_metric.xml
  AutomationFramework/test_cases/templates/ni_next_hop.xml
  AutomationFramework/test_cases/templates/ni_static_prefix.xml
  AutomationFramework/tests/network_instance/test_ni_static.py
Labels: pytest

#64 [pytest] Ni protocol tables tests
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_protocol_tables.yml
  AutomationFramework/test_cases/templates/ni_protocol_tables_connection.xml
  AutomationFramework/test_cases/templates/ni_protocol_tables_connection_default_import_policy.xml
  AutomationFramework/test_cases/templates/ni_protocol_tables_connection_import_policy.xml
  AutomationFramework/test_cases/templates/ni_protocol_tables_creation.xml
  AutomationFramework/tests/network_instance/test_ni_protocol_tables.py
Labels: pytest

#67 [pytest] QoS scheduler tests implemented
  AutomationFramework/page_objects/qos/qos.py
  AutomationFramework/test_cases/qos_scheduler.yml
  AutomationFramework/test_cases/templates/qos_scheduler_max_queue_depth_bytes.xml
  AutomationFramework/test_cases/templates/qos_scheduler_queue.xml
  AutomationFramework/tests/qos/test_qos_scheduler.py
Labels: pytest

#26 [Test Cases] qos_test_cases yaml and xml
  AutomationFramework/page_objects/qos/__init__.py
  AutomationFramework/page_objects/qos/qos.py
  AutomationFramework/test_cases/qos_queue.yml
  AutomationFramework/test_cases/qos_scheduler.yml
  AutomationFramework/test_cases/templates/qos_queue_maxth.xml
  AutomationFramework/test_cases/templates/qos_queue_minth.xml
  AutomationFramework/test_cases/templates/qos_queue_name.xml
  AutomationFramework/test_cases/templates/qos_scheduler_bc.xml
  AutomationFramework/test_cases/templates/qos_scheduler_cir.xml
  AutomationFramework/test_cases/templates/qos_scheduler_id.xml
  AutomationFramework/test_cases/templates/qos_scheduler_max_queue_depth_bytes.xml
  AutomationFramework/test_cases/templates/qos_scheduler_policy_name.xml
  AutomationFramework/test_cases/templates/qos_scheduler_queue.xml
  AutomationFramework/test_cases/templates/qos_scheduler_sequence.xml
  AutomationFramework/test_cases/templates/qos_scheduler_weight.xml
  AutomationFramework/tests/qos/__init__.py
  AutomationFramework/tests/qos/test_qos_queue.py
  AutomationFramework/tests/qos/test_qos_scheduler.py
Labels: test_case

#29 [Test_Cases] New yml rp_community_def
  AutomationFramework/page_objects/routing_policy/__init__.py
  AutomationFramework/page_objects/routing_policy/routing_policy.py
  AutomationFramework/test_cases/rp_community_def.yml
  AutomationFramework/test_cases/templates/rp_community_def_ext_community_member.xml
  AutomationFramework/test_cases/templates/rp_community_def_ext_community_set_name.xml
  AutomationFramework/tests/routing_policy/__init__.py
  AutomationFramework/tests/routing_policy/test_rp_community_def.py
Labels: test_case

#72 [pytest] Hw cpu tests
  AutomationFramework/page_objects/hardware/__init__.py
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_cpu.yml
  AutomationFramework/test_cases/templates/hw_cpu_avg.xml
  AutomationFramework/test_cases/templates/hw_cpu_instant.xml
  AutomationFramework/test_cases/templates/hw_cpu_interval.xml
  AutomationFramework/test_cases/templates/hw_cpu_max.xml
  AutomationFramework/test_cases/templates/hw_cpu_max_time.xml
  AutomationFramework/test_cases/templates/hw_cpu_min.xml
  AutomationFramework/test_cases/templates/hw_cpu_min_time.xml
  AutomationFramework/tests/hardware/__init__.py
  AutomationFramework/tests/hardware/test_hw_cpu.py
Labels: pytest

#37 [Test_Cases] New yml hw_cpu
  AutomationFramework/page_objects/hardware/__init__.py
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_cpu.yml
  AutomationFramework/test_cases/templates/hw_cpu_avg.xml
  AutomationFramework/test_cases/templates/hw_cpu_instant.xml
  AutomationFramework/test_cases/templates/hw_cpu_interval.xml
  AutomationFramework/test_cases/templates/hw_cpu_max.xml
  AutomationFramework/test_cases/templates/hw_cpu_max_time.xml
  AutomationFramework/test_cases/templates/hw_cpu_min.xml
  AutomationFramework/test_cases/templates/hw_cpu_min_time.xml
  AutomationFramework/tests/hardware/__init__.py
  AutomationFramework/tests/hardware/test_hw_cpu.py
Labels: test_case

#42 [Test_Cases] New yml hw_psu
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_psu.yml
  AutomationFramework/test_cases/templates/hw_psu_capacity.xml
  AutomationFramework/test_cases/templates/hw_psu_enabled.xml
  AutomationFramework/test_cases/templates/hw_psu_enabled_state.xml
  AutomationFramework/test_cases/templates/hw_psu_input_current.xml
  AutomationFramework/test_cases/templates/hw_psu_input_voltage.xml
  AutomationFramework/test_cases/templates/hw_psu_output_current.xml
  AutomationFramework/test_cases/templates/hw_psu_output_power.xml
  AutomationFramework/test_cases/templates/hw_psu_output_voltage.xml
  AutomationFramework/tests/hardware/test_hw_psu.py
Labels: test_case

#74 [pytest] hw component tests
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_component.yml
  AutomationFramework/test_cases/templates/hw_component_description.xml
  AutomationFramework/test_cases/templates/hw_component_hardware_version.xml
  AutomationFramework/test_cases/templates/hw_component_id.xml
  AutomationFramework/test_cases/templates/hw_component_location.xml
  AutomationFramework/test_cases/templates/hw_component_mfg_date.xml
  AutomationFramework/test_cases/templates/hw_component_oper_status.xml
  AutomationFramework/test_cases/templates/hw_component_parent.xml
  AutomationFramework/test_cases/templates/hw_component_serial_no.xml
  AutomationFramework/test_cases/templates/hw_component_type.xml
  AutomationFramework/tests/hardware/test_hw_component.py
Labels: pytest

#44 [Test_Case] New yml hw_component
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_component.yml
  AutomationFramework/test_cases/templates/hw_component_description.xml
  AutomationFramework/test_cases/templates/hw_component_hardware_version.xml
  AutomationFramework/test_cases/templates/hw_component_id.xml
  AutomationFramework/test_cases/templates/hw_component_location.xml
  AutomationFramework/test_cases/templates/hw_component_mfg_date.xml
  AutomationFramework/test_cases/templates/hw_component_oper_status.xml
  AutomationFramework/test_cases/templates/hw_component_parent.xml
  AutomationFramework/test_cases/templates/hw_component_serial_no.xml
  AutomationFramework/test_cases/templates/hw_component_type.xml
  AutomationFramework/tests/hardware/test_hw_component.py
Labels: test_case

#45 [Test Cases] New yml hw_subcomponent
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_subcomponent.yml
  AutomationFramework/test_cases/templates/hw_subcomponent_name.xml
  AutomationFramework/test_cases/templates/hw_subcomponent_name_state.xml
  AutomationFramework/tests/hardware/test_hw_subcomponent.py
Labels: test_case

#76 [pytest] Hw properties tests
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_properties.yml
  AutomationFramework/test_cases/templates/hw_properties_name.xml
  AutomationFramework/test_cases/templates/hw_properties_value.xml
  AutomationFramework/tests/hardware/test_hw_properties.py
Labels: pytest

#43 [Test_Cases] New yml hw_properties
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_properties.yml
  AutomationFramework/test_cases/templates/hw_properties_name.xml
  AutomationFramework/test_cases/templates/hw_properties_value.xml
  AutomationFramework/tests/hardware/test_hw_properties.py
Labels: test_case

#77 [pytest] Hw transceiver tests
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_transceiver.yml
  AutomationFramework/test_cases/templates/hw_transceiver_enabled_state.xml
  AutomationFramework/test_cases/templates/hw_transceiver_slot_id.xml
  AutomationFramework/tests/hardware/test_hw_transceiver.py
Labels: pytest

#40 [Test_Cases] New yml hw_transceiver
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_transceiver.yml
  AutomationFramework/test_cases/templates/hw_transceiver_enabled.xml
  AutomationFramework/test_cases/templates/hw_transceiver_enabled_state.xml
  AutomationFramework/test_cases/templates/hw_transceiver_slot_id.xml
  AutomationFramework/tests/hardware/test_hw_transceiver.py
Labels: test_case

#79 [pytest] Hw linecard tests
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_linecard.yml
  AutomationFramework/test_cases/templates/hw_linecard_power_admin_state.xml
  AutomationFramework/tests/hardware/test_hw_linecard.py
Labels: pytest

#39 [Test_Cases] New yml hw_linecard
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_linecard.yml
  AutomationFramework/test_cases/templates/hw_linecard_power_admin.xml
  AutomationFramework/test_cases/templates/hw_linecard_power_admin_state.xml
  AutomationFramework/tests/hardware/test_hw_linecard.py
Labels: test_case

#81 [Pytests] Name changed
  AutomationFramework/tests/hardware/test_hw_linecard.py
Labels: pytest

#38 [Test_Cases] New yml hw_fan
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_fan.yml
  AutomationFramework/test_cases/templates/hw_fan_speed.xml
  AutomationFramework/tests/hardware/test_hw_fan.py
Labels: test_case

#83 [pytest] HW config tests
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_config.yml
  AutomationFramework/tests/hardware/test_hw_config.py
Labels: pytest

#36 [Test_Cases] New yml hw_config
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_config.yml
  AutomationFramework/test_cases/templates/hw_config_name.xml
  AutomationFramework/tests/hardware/test_hw_config.py
Labels: test_case

#22 [Test_Cases] If lag
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_lag.yml
  AutomationFramework/test_cases/templates/if_lag_min_links.xml
  AutomationFramework/test_cases/templates/if_lag_type.xml
  AutomationFramework/tests/test_if_lag.py
Labels: test_case

#86 [pytest] Reports
  AutomationFramework/.gitignore
  AutomationFramework/README.md
  AutomationFramework/test_cases/if_config.yml
  AutomationFramework/test_cases/if_ethernet.yml
  AutomationFramework/test_cases/if_status.yml
Labels: pytest

#34 [Test Cases] If ethernet.
  AutomationFramework/test_cases/if_ethernet.yml
  AutomationFramework/test_cases/templates/if_ethernet_aggregate_id.xml
  AutomationFramework/test_cases/templates/if_ethernet_lag_create.xml
Labels: test_case

#93 [pytest] Lists fix
  AutomationFramework/test_cases/if_subif.yml
  AutomationFramework/test_cases/ni_ospf.yml
  AutomationFramework/tests/hardware/test_hw_config.py
  AutomationFramework/tests/hardware/test_hw_linecard.py
  AutomationFramework/tests/network_instance/test_ni_bgp.py
  AutomationFramework/tests/network_instance/test_ni_config.py
  AutomationFramework/tests/network_instance/test_ni_connection_point.py
  AutomationFramework/tests/network_instance/test_ni_encapsulation.py
  AutomationFramework/tests/network_instance/test_ni_fdb.py
  AutomationFramework/tests/network_instance/test_ni_ospf.py
  AutomationFramework/tests/network_instance/test_ni_protocol_instances.py
  AutomationFramework/tests/network_instance/test_ni_protocol_tables.py
  AutomationFramework/tests/network_instance/test_ni_static.py
  AutomationFramework/tests/qos/test_qos_queue.py
  AutomationFramework/tests/qos/test_qos_scheduler.py
  AutomationFramework/tests/routing_policy/test_rp_community_def.py
  AutomationFramework/tests/routing_policy/test_rp_policy_def.py
  AutomationFramework/tests/test_if_ethernet.py
  AutomationFramework/tests/test_if_subif.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest
