Repository sbarguil/Testing-framework, pull requests merged in 2020-09, with the labels that each got.

#97 [pytest] Multiple rpcs suport and if ethernet tests fixed
  AutomationFramework/capabilities.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_ethernet.yml
  AutomationFramework/test_cases/templates/if_ethernet_aggregate_id.xml
  AutomationFramework/test_cases/templates/if_ethernet_lag_create.xml
  AutomationFramework/test_cases/templates/if_ethernet_port_speed_state.xml
  AutomationFramework/tests/base_test.py
  AutomationFramework/tests/interfaces/__init__.py
  AutomationFramework/tests/interfaces/test_if_config.py
  AutomationFramework/tests/interfaces/test_if_ethernet.py
  AutomationFramework/tests/interfaces/test_if_lag.py
  AutomationFramework/tests/interfaces/test_if_status.py
  AutomationFramework/tests/interfaces/test_if_subif.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest

#90 [Test Cases] Ni t ldp review
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_t_ldp.yml
  AutomationFramework/test_cases/templates/ni_t_ldp_afi_name.xml
  AutomationFramework/test_cases/templates/ni_t_ldp_enabled.xml
  AutomationFramework/test_cases/templates/ni_t_ldp_local_address.xml
  AutomationFramework/test_cases/templates/ni_t_ldp_remote_address.xml
  AutomationFramework/tests/network_instance/test_ni_t_ldp.py
Labels: For develop

#87 Review if_subif test_case
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_subif.yml
  AutomationFramework/test_cases/templates/if_subif_dhcp_client.xml
  AutomationFramework/test_cases/templates/if_subif_ip_state.xml
  AutomationFramework/test_cases/templates/if_subif_mtu.xml
  AutomationFramework/test_cases/templates/if_subif_origin.xml
  AutomationFramework/tests/interfaces/test_if_subif.py
Labels: For develop

#84 [Review issues hw_subcomponent] fix yml hw_subcomponent.
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_subcomponent.yml
  AutomationFramework/test_cases/templates/hw_component_name.xml
  AutomationFramework/tests/hardware/test_hw_subcomponent.py
Labels: For develop

#23 [Test_Cases] New YML if_gre
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_gre.yml
  AutomationFramework/test_cases/templates/if_gre_dst.xml
  AutomationFramework/test_cases/templates/if_gre_ip_prefix_length.xml
  AutomationFramework/test_cases/templates/if_gre_mtu.xml
  AutomationFramework/test_cases/templates/if_gre_src.xml
  AutomationFramework/test_cases/templates/if_gre_ttl.xml
  AutomationFramework/tests/interfaces/test_if_gre.py
Labels: test_case

#85 [Review issues if_config] Fix If config review.
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/if_config.yml
  AutomationFramework/test_cases/templates/if_config_loopback_mode.xml
  AutomationFramework/tests/interfaces/test_if_config.py
Labels: For develop

#91 [Test Cases]review yml ni_bgp
  AutomationFramework/README_Change_params.md
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/page_objects/routing_policy/routing_policy.py
  AutomationFramework/test_cases/ni_bgp.yml
  AutomationFramework/test_cases/templates/ni_bgp_description.xml
  AutomationFramework/test_cases/templates/ni_bgp_enabled.xml
  AutomationFramework/test_cases/templates/ni_bgp_export_policy.xml
  AutomationFramework/test_cases/templates/ni_bgp_import_policy.xml
  AutomationFramework/test_cases/templates/ni_bgp_local_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_multihop_ttl.xml
  AutomationFramework/test_cases/templates/ni_bgp_neighbor_address.xml
  AutomationFramework/test_cases/templates/ni_bgp_peer_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_peer_type.xml
  AutomationFramework/test_cases/templates/ni_bgp_remove_private_as.xml
  AutomationFramework/test_cases/templates/ni_bgp_router_id.xml
  AutomationFramework/tests/network_instance/test_ni_bgp.py
Labels: For develop

#102 [pytest] Tests unskipped
  AutomationFramework/tests/hardware/test_hw_linecard.py
  AutomationFramework/tests/hardware/test_hw_transceiver.py
Labels: pytest

#95 [Test Cases] review yml qos_scheduler
  AutomationFramework/page_objects/qos/qos.py
  AutomationFramework/test_cases/qos_scheduler.yml
  AutomationFramework/test_cases/templates/qos_scheduler_queue.xml
  AutomationFramework/tests/qos/test_qos_scheduler.py
Labels: For develop

#92 [Test Cases ] review yml ni_ospf Subinterface.
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_ospf.yml
  AutomationFramework/test_cases/templates/ni_ospf_subinterface.xml
  AutomationFramework/test_cases/templates/ni_ospf_subinterface_name.xml
  AutomationFramework/tests/network_instance/test_ni_ospf.py
Labels: For develop

#88 [Review Test_Case ni_rt_policy] Ni rt policy review
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/page_objects/routing_policy/routing_policy.py
  AutomationFramework/test_cases/ni_rt_policy.yml
  AutomationFramework/test_cases/templates/ni_rt_policy_export-policy.xml
  AutomationFramework/test_cases/templates/ni_rt_policy_export_policy.xml
  AutomationFramework/test_cases/templates/ni_rt_policy_import_policy.xml
  AutomationFramework/test_cases/templates/ni_rt_policy_name.xml
  AutomationFramework/tests/network_instance/test_ni_rt_policy.py
Labels: For develop

#89 [Test_Case] review yml ni_interface.yml
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/ni_interface.yml
  AutomationFramework/test_cases/templates/ni_interface_id.xml
  AutomationFramework/test_cases/templates/ni_interface_interface.xml
  AutomationFramework/test_cases/templates/ni_interface_subif.xml
  AutomationFramework/test_cases/templates/ni_interface_subinterface.xml
  AutomationFramework/tests/network_instance/test_ni_interface.py
Labels: For develop

#94 [Test Cases] review yml ni_protocol_tables
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/page_objects/routing_policy/routing_policy.py
  AutomationFramework/test_cases/ni_protocol_tables.yml
  AutomationFramework/test_cases/templates/ni_protocol_policy_name.xml
  AutomationFramework/test_cases/templates/ni_protocol_tables_connection_import_policy.xml
  AutomationFramework/tests/network_instance/test_ni_protocol_tables.py
Labels: For develop

#106 [pytest] Requests output excel file feature
  AutomationFramework/excel_logs/cumulative_log.xlsx
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/tests/base_test.py
  AutomationFramework/utils/excel_logger.py
  AutomationFramework/utils/rpc_automator_2.py
Labels: pytest

#110 [pytest] Integration of report generation with logs
  AutomationFramework/README.md
  AutomationFramework/excel_logs/cumulative_log.xlsx
  AutomationFramework/execute_sub_set.py
  AutomationFramework/generate_report.py
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/params/SBI_params_test_ Almagro_Sept_2020_v1.xlsx
  AutomationFramework/tests/base_test.py
Labels: pytest

#41 [Test_Cases] New yml hw_port
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/test_cases/hw_port.yml
  AutomationFramework/test_cases/templates/hw_port_channel_speed.xml
  AutomationFramework/test_cases/templates/hw_port_channel_speed_state.xml
  AutomationFramework/test_cases/templates/hw_port_num_channels.xml
  AutomationFramework/test_cases/templates/hw_port_num_channels_state.xml
  AutomationFramework/tests/hardware/test_hw_port.py
Labels: test_case

#103 if_status_type and ni_bgp_multihop changes
  AutomationFramework/page_objects/interfaces/interfaces.py
  AutomationFramework/page_objects/network_instance/network_intance.py
  AutomationFramework/test_cases/if_status.yml
  AutomationFramework/test_cases/ni_bgp.yml
  AutomationFramework/test_cases/templates/if_status_type.xml
  AutomationFramework/test_cases/templates/if_subif_type.xml
  AutomationFramework/test_cases/templates/ni_bgp_multihop_ttl.xml
  AutomationFramework/test_cases/templates/ni_bgp_peer_as.xml
  AutomationFramework/tests/interfaces/test_if_status.py
Labels: For develop

#96 [Test_Cases] review yml rp_policy_def
  AutomationFramework/page_objects/base/base_page_object.py
  AutomationFramework/page_objects/routing_policy/routing_policy.py
  AutomationFramework/params/SBI_params_test_ Almagro_Sept_2020_v1.xlsx
  AutomationFramework/test_cases/rp_policy_def.yml
  AutomationFramework/test_cases/templates/rp_policy_def_create_ext_community_set.xml
  AutomationFramework/test_cases/templates/rp_policy_def_create_ext_community_set.xml.xml
  AutomationFramework/test_cases/templates/rp_policy_def_ext_community_set.xml
  AutomationFramework/test_cases/templates/rp_policy_def_match_set_options.xml
  AutomationFramework/tests/routing_policy/test_rp_policy_def.py
  AutomationFramework/utils/excel_logger.py
Labels: For develop

#104 [Test_Case Review] Only get subcomponent name.
  AutomationFramework/page_objects/hardware/hardware.py
  AutomationFramework/test_cases/hw_subcomponent.yml
  AutomationFramework/test_cases/templates/hw_subcomponent_name.xml
  AutomationFramework/test_cases/templates/hw_subcomponent_name_state.xml
  AutomationFramework/tests/hardware/test_hw_subcomponent.py
Labels: For develop
